In [23]:
import pandas as pd
import numpy as np

data = pd.read_csv('..//data//raw//SGJobData.csv')

In [24]:
data.info()
# display(data.head())
# display(data.tail())
# display(data[data['metadata_expiryDate'].isnull()])
# display(data[data['metadata_newPostingDate'].isnull()])
# display(data[data['metadata_originalPostingDate'].isnull()])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048585 entries, 0 to 1048584
Data columns (total 22 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  object
 3   metadata_isPostedOnBehalf           1048585 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  object
 6   metadata_originalPostingDate        1044597 non-null  object
 7   metadata_repostCount                1048585 non-null  int64
 8   metadata_totalNumberJobApplication  1048585 non-null  int64
 9   metadata_totalNumberOfView          1048585 non-null  int64
 10  minimumYearsExperience              1048585 non-null  int64
 11  numberOfVacancies                   1048585 non-null  int64
 12  occupationId                        0 non-null        float64
 13  positionLevels                      1044597 non-null  object
 14  postedCompany_name                  1044597 non-null  object
 15  salary_maximum                      1048585 non-null  int64
 16  salary_minimum                      1048585 non-null  int64
 17  salary_type                         1044597 non-null  object
 18  status_id                           1048585 non-null  int64
 19  status_jobStatus                    1044597 non-null  object
 20  title                               1044597 non-null  object
 21  average_salary                      1048585 non-null  float64
dtypes: bool(1), float64(2), int64(8), object(11)
memory usage: 169.0+ MB

In [25]:
data = data.dropna(subset=['metadata_originalPostingDate', 'metadata_newPostingDate', 'metadata_expiryDate', 'metadata_jobPostId', 'postedCompany_name']).reset_index(drop=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044597 entries, 0 to 1044596
Data columns (total 22 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  object
 3   metadata_isPostedOnBehalf           1044597 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  object
 6   metadata_originalPostingDate        1044597 non-null  object
 7   metadata_repostCount                1044597 non-null  int64
 8   metadata_totalNumberJobApplication  1044597 non-null  int64
 9   metadata_totalNumberOfView          1044597 non-null  int64
 10  minimumYearsExperience              1044597 non-null  int64
 11  numberOfVacancies                   1044597 non-null  int64
 12  occupationId                        0 non-null        float64
 13  positionLevels                      1044597 non-null  object
 14  postedCompany_name                  1044597 non-null  object
 15  salary_maximum                      1044597 non-null  int64
 16  salary_minimum                      1044597 non-null  int64
 17  salary_type                         1044597 non-null  object
 18  status_id                           1044597 non-null  int64
 19  status_jobStatus                    1044597 non-null  object
 20  title                               1044597 non-null  object
 21  average_salary                      1044597 non-null  float64
dtypes: bool(1), float64(2), int64(8), object(11)
memory usage: 168.4+ MB

In [26]:
# Convert date fields into datetime format

data['metadata_expiryDate'] = pd.to_datetime(data['metadata_expiryDate'], errors='coerce', cache=False)
data['metadata_newPostingDate'] = pd.to_datetime(data['metadata_newPostingDate'], errors='coerce', cache=False)
data['metadata_originalPostingDate'] = pd.to_datetime(data['metadata_originalPostingDate'], errors='coerce', cache=False)

# data['metadata_expiryDate'].info()
# data['metadata_newPostingDate'].info()
# data['metadata_originalPostingDate'].info()

In [27]:
data.info()
# display(data.describe().apply(lambda x: x.apply('{:.2f}'.format)))
# data.describe(include=['object', 'bool', 'datetime'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044597 entries, 0 to 1044596
Data columns (total 22 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  datetime64[ns]
 3   metadata_isPostedOnBehalf           1044597 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  datetime64[ns]
 6   metadata_originalPostingDate        1044597 non-null  datetime64[ns]
 7   metadata_repostCount                1044597 non-null  int64
 8   metadata_totalNumberJobApplication  1044597 non-null  int64
 9   metadata_totalNumberOfView          1044597 non-null  int64
 10  minimumYearsExperience              1044597 non-null  int64
 11  numberOfVacancies                   1044597 non-null  int64
 12  occupationId                        0 non-null        float64
 13  positionLevels                      1044597 non-null  object
 14  postedCompany_name                  1044597 non-null  object
 15  salary_maximum                      1044597 non-null  int64
 16  salary_minimum                      1044597 non-null  int64
 17  salary_type                         1044597 non-null  object
 18  status_id                           1044597 non-null  int64
 19  status_jobStatus                    1044597 non-null  object
 20  title                               1044597 non-null  object
 21  average_salary                      1044597 non-null  float64
dtypes: bool(1), datetime64[ns](3), float64(2), int64(8), object(8)
memory usage: 168.4+ MB

In [58]:
# data.drop(columns=['category'], inplace=True)
# data.head()

In [ ]:
# Parse json strings into valide Python lists; skip if already parsed
# drop the occupationId column as the the entire column is null and not useful for analysis.

import ast

# Parse JSON strings into Python lists; skip if already parsed
data['categories'] = data['categories'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)
# data.drop(columns=['occupationId'], inplace=True)

# data['categories'].info()
data.info()
display(data.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044597 entries, 0 to 1044596
Data columns (total 21 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   categories                          1044597 non-null  object
 1   employmentTypes                     1044597 non-null  object
 2   metadata_expiryDate                 1044597 non-null  datetime64[ns]
 3   metadata_isPostedOnBehalf           1044597 non-null  bool
 4   metadata_jobPostId                  1044597 non-null  object
 5   metadata_newPostingDate             1044597 non-null  datetime64[ns]
 6   metadata_originalPostingDate        1044597 non-null  datetime64[ns]
 7   metadata_repostCount                1044597 non-null  int64
 8   metadata_totalNumberJobApplication  1044597 non-null  int64
 9   metadata_totalNumberOfView          1044597 non-null  int64
 10  minimumYearsExperience              1044597 non-null  int64
 11  numberOfVacancies                   1044597 non-null  int64
 12  positionLevels                      1044597 non-null  object
 13  postedCompany_name                  1044597 non-null  object
 14  salary_maximum                      1044597 non-null  int64
 15  salary_minimum                      1044597 non-null  int64
 16  salary_type                         1044597 non-null  object
 17  status_id                           1044597 non-null  int64
 18  status_jobStatus                    1044597 non-null  object
 19  title                               1044597 non-null  object
 20  average_salary                      1044597 non-null  float64
dtypes: bool(1), datetime64[ns](3), float64(1), int64(8), object(8)
memory usage: 160.4+ MB

,categories,employmentTypes,metadata_expiryDate,metadata_isPostedOnBehalf,metadata_jobPostId,metadata_newPostingDate,metadata_originalPostingDate,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,...,numberOfVacancies,positionLevels,postedCompany_name,salary_maximum,salary_minimum,salary_type,status_id,status_jobStatus,title,average_salary
0,"[{'id': 13, 'category': 'Environment / Health'...",Permanent,2023-05-08,False,MCF-2023-0252866,2023-04-08,2023-03-30,2,5,151,...,1,Executive,WORKSTONE PTE. LTD.,2800,2000,Monthly,0,Closed,Food Technologist - Clementi | Entry Level | U...,2400.0
1,"[{'id': 21, 'category': 'Information Technolog...",Permanent,2023-05-08,False,MCF-2023-0273977,2023-04-08,2023-04-08,0,0,55,...,2,Executive,TRUST RECRUIT PTE. LTD.,5500,4000,Monthly,0,Closed,"Software Engineer (Fab Support) (Java, CIM, Up...",4750.0
2,"[{'id': 33, 'category': 'Repair and Maintenanc...",Full Time,2023-04-22,False,MCF-2023-0273994,2023-04-08,2023-04-08,0,7,99,...,1,Senior Executive,PU TIEN SERVICES PTE. LTD.,4600,3800,Monthly,0,Closed,Senior Technician,4200.0
3,"[{'id': 21, 'category': 'Information Technolog...",Permanent,2023-05-08,False,MCF-2023-0273991,2023-04-08,2023-04-08,0,6,113,...,1,Senior Executive,TRUST RECRUIT PTE. LTD.,10000,5000,Monthly,0,Closed,"Senior .NET Developer (.NET Core, MVC, MVVC, S...",7500.0
4,"[{'id': 2, 'category': 'Admin / Secretarial'}]",Full Time,2023-05-08,False,MCF-2023-0273976,2023-04-08,2023-04-08,0,3,99,...,3,Non-executive,EATZ CATERING SERVICES PTE. LTD.,3400,2400,Monthly,0,Closed,Sales / Admin Cordinator,2900.0

## Data Cleaning Pipeline - Start Here

### Common Validation/Parsing Functions

In [52]:
import json
import pandas as pd

# Parse JSON strings into Python lists; skip if already parsed
def _parse_categories(value):
        if isinstance(value, list):
            return value
        if isinstance(value, str):
            value = value.strip()
            if not value:
                return []
            try:
                parsed = json.loads(value)
            except json.JSONDecodeError as e:
                raise ValueError(f"Malformed JSON in categories: {value[:200]}") from e
            return parsed if isinstance(parsed, list) else [parsed]
        if pd.isna(value):
            return []
        raise ValueError(f"Unsupported categories value type: {type(value).__name__}")

def validate_non_negative(chunk, columns):
    """Raise an error when a specified numeric column contains negative values."""
    missing_columns = [column for column in columns if column not in chunk.columns]
    if missing_columns:
        raise KeyError(f"Missing columns for non-negative validation: {missing_columns}")

    for column in columns:
        negative_count = (chunk[column] < 0).sum()
        if negative_count:
            raise ValueError(f"{column}: {negative_count} negative values are not allowed.")

### Data Cleaning

In [56]:
import json
from pathlib import Path

source_path = Path("../data/raw/SGJobData.csv")
output_path = Path("../data/processed/SGJobData_cleaned.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)
chunk_size = 100_000

expected_dtypes = {
    "metadata_isPostedOnBehalf": "bool",
    "metadata_repostCount": "int64",
    "metadata_totalNumberJobApplication": "int64",
    "metadata_totalNumberOfView": "int64",
    "minimumYearsExperience": "int64",
    "numberOfVacancies": "int64",
    "salary_maximum": "float64",
    "salary_minimum": "float64",
    "average_salary": "float64",
}
required_columns = [
    "metadata_originalPostingDate", "metadata_newPostingDate",
    "metadata_expiryDate", "metadata_jobPostId", "postedCompany_name",
]
date_columns = [
    "metadata_expiryDate", "metadata_newPostingDate", "metadata_originalPostingDate",
]


float_columns = [
    column
    for column, dtype in expected_dtypes.items()
    if dtype == "float64"
]

non_negative_columns = [
    "average_salary",
    "salary_minimum",
    "salary_maximum",
]


int_columns = [column for column, dtype in expected_dtypes.items() if dtype == "int64"]

def clean_chunk(chunk):

    missing_columns = [column for column in [*required_columns, *expected_dtypes] if column not in chunk.columns]
    if missing_columns:
        raise KeyError(f"Missing columns: {missing_columns}")

    chunk = chunk.dropna(subset=required_columns, how="all").copy()

    for column in date_columns:
        chunk[column] = pd.to_datetime(chunk[column], errors="coerce", cache=False)

    bool_column = "metadata_isPostedOnBehalf"
    parsed_bool = (
        chunk[bool_column].astype(str).str.strip().str.lower()
        .map({"true": True, "false": False, "1": True, "0": False, "yes": True, "no": False})
    )
    if parsed_bool.isna().any():
        raise ValueError(f"{bool_column}: {parsed_bool.isna().sum()} invalid values cannot be parsed to bool.")
    chunk[bool_column] = parsed_bool.astype(bool)

    for column in int_columns:
        parsed = pd.to_numeric(chunk[column], errors="coerce")
        if parsed.isna().any():
            raise ValueError(f"{column}: {parsed.isna().sum()} invalid values cannot be parsed to int64.")
        chunk[column] = parsed.astype("int64")

    for float_column in float_columns:
        parsed_float = pd.to_numeric(chunk[float_column], errors="coerce")
        if parsed_float.isna().any():
            raise ValueError(f"{float_column}: {parsed_float.isna().sum()} invalid values cannot be parsed to float64.")
        chunk[float_column] = parsed_float.astype("float64")
    
    validate_non_negative(chunk, non_negative_columns)

    dtype_check = chunk[list(expected_dtypes)].dtypes.astype(str).to_dict()
    assert dtype_check == expected_dtypes, "Type validation failed for one or more columns."
    chunk = chunk.drop(columns=["occupationId"], errors="ignore")

    chunk['metadata_expiryDate'] = pd.to_datetime(chunk['metadata_expiryDate'], errors='coerce', cache=False)
    chunk['metadata_newPostingDate'] = pd.to_datetime(chunk['metadata_newPostingDate'], errors='coerce', cache=False)
    chunk['metadata_originalPostingDate'] = pd.to_datetime(chunk['metadata_originalPostingDate'], errors='coerce', cache=False)

    chunk["categories"] = chunk["categories"].apply(_parse_categories)

    return chunk

rows_written = 0
for chunk_number, chunk in enumerate(pd.read_csv(source_path, chunksize=chunk_size)):
    cleaned_chunk = clean_chunk(chunk)
    cleaned_chunk.to_csv(output_path, mode="w" if chunk_number == 0 else "a", header=chunk_number == 0, index=False)
    rows_written += len(cleaned_chunk)
    # display(cleaned_chunk.info())

print(f"Streaming clean completed: {rows_written:,} rows written to {output_path}.")

Streaming clean completed: 1,044,597 rows written to ../data/processed/SGJobData_cleaned.csv.

## Data Features Generation Start Here

In [58]:
from pathlib import Path
import ast
import pandas as pd

def load_categories(value):
    try:
        parsed = ast.literal_eval(value)
    except (SyntaxError, ValueError) as error:
        raise ValueError(f"Invalid Python list in categories: {value[:200]}") from error

    if not isinstance(parsed, list):
        raise ValueError("categories must contain a JSON list.")
    return parsed


clean_path = Path("../data/processed/SGJobData_cleaned.csv")

for chunk in pd.read_csv(
    clean_path,
    chunksize=100_000,
    parse_dates=[
        "metadata_expiryDate",
        "metadata_newPostingDate",
        "metadata_originalPostingDate",
    ],
    converters={"categories": load_categories},
):
    with pd.option_context("display.float_format", "{:,.2f}".format):
        display(chunk.describe())

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,status_id,average_salary
count,"100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00"
mean,0.35,11.20,133.61,2.78,2.64,"5,587.96","3,747.77",0.00,"4,667.86"
std,0.66,24.03,176.72,2.46,12.24,"31,908.64","2,661.90",0.00,"16,169.55"
min,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00
25%,0.00,1.00,41.00,1.00,1.00,"3,200.00","2,500.00",0.00,"2,850.00"
50%,0.00,4.00,79.00,2.00,1.00,"4,500.00","3,000.00",0.00,"3,750.00"
75%,0.00,11.00,159.00,4.00,2.00,"6,500.00","4,500.00",0.00,"5,500.00"
max,2.00,"1,048.00","8,190.00",56.00,999.00,"10,000,000.00","180,000.00",0.00,"5,000,750.00"

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,status_id,average_salary
count,"100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00"
mean,0.15,7.67,87.53,2.77,2.61,"5,523.05","3,761.93",0.00,"4,642.49"
std,0.44,18.87,129.46,2.53,10.81,"4,273.95","2,707.05",0.00,"3,407.93"
min,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00
25%,0.00,0.00,26.00,1.00,1.00,"3,200.00","2,500.00",0.00,"2,900.00"
50%,0.00,2.00,49.00,2.00,1.00,"4,500.00","3,000.00",0.00,"3,750.00"
75%,0.00,7.00,100.00,4.00,2.00,"6,500.00","4,500.00",0.00,"5,500.00"
max,2.00,"1,342.00","7,491.00",76.00,999.00,"225,000.00","160,944.00",0.00,"187,500.00"

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,status_id,average_salary
count,"100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00"
mean,0.04,0.61,9.52,2.83,2.57,"5,592.88","3,825.34",0.00,"4,709.11"
std,0.23,4.52,39.81,2.60,8.18,"4,686.54","2,996.91",0.00,"3,752.12"
min,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00
25%,0.00,0.00,1.00,1.00,1.00,"3,200.00","2,500.00",0.00,"2,850.00"
50%,0.00,0.00,2.00,2.00,1.00,"4,500.00","3,000.00",0.00,"3,750.00"
75%,0.00,0.00,6.00,4.00,2.00,"6,500.00","4,500.00",0.00,"5,500.00"
max,2.00,421.00,"2,040.00",87.00,999.00,"380,000.00","325,000.00",0.00,"352,500.00"

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,status_id,average_salary
count,"100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00"
mean,0.02,0.35,5.31,2.79,2.78,"5,833.12","3,807.46",0.00,"4,820.29"
std,0.15,4.13,33.43,2.54,11.33,"80,235.90","3,230.55",0.00,"40,240.20"
min,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00
25%,0.00,0.00,0.00,1.00,1.00,"3,300.00","2,500.00",0.00,"2,900.00"
50%,0.00,0.00,2.00,2.00,1.00,"4,500.00","3,000.00",0.00,"3,750.00"
75%,0.00,0.00,4.00,4.00,2.00,"6,500.00","4,500.00",0.00,"5,500.00"
max,2.00,"1,052.00","7,521.00",88.00,999.00,"25,330,000.00","255,000.00",0.00,"12,666,400.00"

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,status_id,average_salary
count,"100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00"
mean,0.00,0.60,7.61,2.78,2.69,"5,570.16","3,806.04",0.00,"4,688.10"
std,0.07,3.20,21.57,2.50,10.89,"4,750.08","3,019.87",0.00,"3,790.19"
min,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00
25%,0.00,0.00,0.00,1.00,1.00,"3,300.00","2,500.00",0.00,"2,900.00"
50%,0.00,0.00,2.00,2.00,1.00,"4,500.00","3,000.00",0.00,"3,850.00"
75%,0.00,1.00,7.00,4.00,3.00,"6,500.00","4,500.00",0.00,"5,500.00"
max,2.00,465.00,"2,014.00",50.00,999.00,"365,000.00","250,000.00",0.00,"305,000.00"

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,status_id,average_salary
count,"100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00"
mean,0.00,0.24,4.13,2.74,2.86,"5,573.04","3,794.35",0.00,"4,683.69"
std,0.05,0.89,9.63,2.50,15.34,"5,743.61","2,938.74",0.00,"4,053.44"
min,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00
25%,0.00,0.00,0.00,1.00,1.00,"3,200.00","2,500.00",0.00,"2,900.00"
50%,0.00,0.00,2.00,2.00,1.00,"4,500.00","3,000.00",0.00,"3,750.00"
75%,0.00,0.00,5.00,4.00,2.00,"6,500.00","4,500.00",0.00,"5,500.00"
max,2.00,133.00,833.00,55.00,999.00,"1,000,000.00","250,000.00",0.00,"500,000.50"

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,status_id,average_salary
count,"100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00"
mean,0.00,0.25,4.25,2.76,2.81,"5,545.83","3,789.58",0.00,"4,667.70"
std,0.02,0.62,7.91,2.48,10.30,"4,966.43","3,448.23",0.00,"4,127.70"
min,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00
25%,0.00,0.00,0.00,1.00,1.00,"3,300.00","2,500.00",0.00,"2,900.00"
50%,0.00,0.00,2.00,2.00,1.00,"4,500.00","3,000.00",0.00,"3,800.00"
75%,0.00,0.00,5.00,4.00,3.00,"6,400.00","4,300.00",0.00,"5,288.75"
max,2.00,94.00,768.00,31.00,999.00,"400,000.00","350,000.00",0.00,"375,000.00"

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,status_id,average_salary
count,"100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00"
mean,0.00,0.29,5.78,2.79,2.75,"5,676.52","3,887.58",0.00,"4,782.05"
std,0.02,0.61,8.89,2.56,13.06,"5,156.13","3,200.24",0.00,"4,079.61"
min,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00
25%,0.00,0.00,1.00,1.00,1.00,"3,400.00","2,500.00",0.00,"3,000.00"
50%,0.00,0.00,3.00,2.00,1.00,"4,500.00","3,000.00",0.00,"3,900.00"
75%,0.00,1.00,7.00,4.00,3.00,"6,500.00","4,500.00",0.00,"5,500.00"
max,2.00,109.00,543.00,62.00,999.00,"370,000.00","185,000.00",0.00,"277,500.00"

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,status_id,average_salary
count,"100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00"
mean,0.00,0.34,7.53,2.82,2.60,"5,613.77","3,867.34",0.00,"4,740.56"
std,0.02,0.48,10.32,2.58,9.86,"5,102.81","3,309.48",0.00,"4,128.25"
min,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00
25%,0.00,0.00,2.00,1.00,1.00,"3,400.00","2,500.00",0.00,"2,950.00"
50%,0.00,0.00,4.00,2.00,1.00,"4,500.00","3,000.00",0.00,"3,850.00"
75%,0.00,1.00,9.00,4.00,2.00,"6,500.00","4,500.00",0.00,"5,500.00"
max,1.00,7.00,256.00,87.00,999.00,"464,000.00","340,000.00",0.00,"376,000.00"

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,status_id,average_salary
count,"100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00"
mean,0.00,0.63,11.39,2.83,2.60,"5,718.53","3,930.28",0.00,"4,824.41"
std,0.02,2.26,18.29,2.54,8.89,"5,367.49","3,307.84",0.00,"4,205.59"
min,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00
25%,0.00,0.00,2.00,1.00,1.00,"3,500.00","2,500.00",0.00,"3,000.00"
50%,0.00,0.00,6.00,2.00,1.00,"4,500.00","3,000.00",0.00,"3,950.00"
75%,0.00,1.00,14.00,4.00,3.00,"6,500.00","4,500.00",0.00,"5,500.00"
max,2.00,124.00,634.00,33.00,999.00,"552,007.00","210,000.00",0.00,"277,553.50"

,metadata_repostCount,metadata_totalNumberJobApplication,metadata_totalNumberOfView,minimumYearsExperience,numberOfVacancies,salary_maximum,salary_minimum,status_id,average_salary
count,"44,597.00","44,597.00","44,597.00","44,597.00","44,597.00","44,597.00","44,597.00","44,597.00","44,597.00"
mean,0.00,0.49,8.51,2.80,2.61,"8,479.76","4,011.73",0.00,"6,245.74"
std,0.03,11.35,53.33,2.68,11.23,"205,019.95","4,560.62",0.00,"103,737.22"
min,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00
25%,0.00,0.00,2.00,1.00,1.00,"3,500.00","2,500.00",0.00,"3,000.00"
50%,0.00,0.00,4.00,2.00,1.00,"4,650.00","3,000.00",0.00,"4,000.00"
75%,0.00,1.00,10.00,4.00,3.00,"6,700.00","4,500.00",0.00,"5,700.00"
max,2.00,"1,199.00","8,103.00",88.00,999.00,"23,712,119.00","324,072.00",0.00,"11,863,419.00"